language: node_js

os:
    - linux
    - osx

node_js:
    - "8.11"
    - "9.0"
    - "10.0"

language: bash

install:
    - wget https://raw.github.com/lehmannro/assert.sh/v1.1/assert.sh && chmod +x assert.sh

script:
    - ./tests.sh

