language: node_js

os:
    - linux
    - osx

node_js:
    - "8.11"
    - "9.0"
    - "10.0"

before_script:
    - npm run build
    - mkdir -p /home/travis/.config/sql-lint && touch /home/travis/.config/sql-lint/config.json
    - chmod a+x ./dist/src/main.js
