version: '3'
services:
  mysql:
    # image: mysql:5
    restart: always
    build:
        context: ./
        dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
volumes:
  mysql: ~
